In [1]:
print("hello world")

hello world


In [1]:
import numpy as np

In [5]:
one_dimensional_array = np.array([1, 2, 3, 4, 5])
print (one_dimensional_array)

[1 2 3 4 5]


In [2]:
arr=np.array([10,12])
print(arr)

[10 12]


In [3]:
arr1=np.array(3)

In [4]:
print(arr1)

3


In [5]:
arr2=np.arange(3)
print(arr2)

[0 1 2]


In [6]:
c=np.arange(1,20,3)
print(c)

[ 1  4  7 10 13 16 19]


In [7]:
d=np.linspace(1,20,3)
print(d)

[ 1.  10.5 20. ]


In [9]:
e=np.linspace(1,20,3,dtype=int)
print(e)

[ 1 10 20]


In [10]:
two_dimensional_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(two_dimensional_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
c_int=np.arange(1,20,3,dtype=int)
print(c_int)

[ 1  4  7 10 13 16 19]


In [12]:
b_float=np.arange(3,dtype=float)
print(b_float)

[0. 1. 2.]


In [14]:
char_array = np.array(['Welcome to Math for Ml'])
print(char_array)
print(char_array.dtype)

['Welcome to Math for Ml']
<U22


In [15]:
ones_arr=np.ones((3))

In [16]:
print(ones_arr)

[1. 1. 1.]


In [17]:
zeros_arr=np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [18]:
empt_arr=np.empty(3)
print(empt_arr)

[0. 0. 0.]


In [19]:
rand_arr=np.random.rand(3)
print(rand_arr)

[0.35472951 0.85149755 0.49330046]


In [20]:
two_dimensional_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(two_dimensional_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
print(two_dimensional_array[0,0])

1


In [22]:
print(two_dimensional_array[0,1])

2


In [25]:
one_demensional_array=np.array([1,2,3,4,5,6,8,9,3])

multi_dimensional_array=np.reshape(one_demensional_array,
                                   (3,3)
                                   )
print(multi_dimensional_array)

[[1 2 3]
 [4 5 6]
 [8 9 3]]


In [26]:
multi_dimensional_array.ndim

2

In [27]:
multi_dimensional_array.shape

(3, 3)

In [28]:
multi_dimensional_array.size

9

In [29]:
#array math operations

In [30]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [31]:
c=a+b
print(c)

[5 7 9]


In [32]:
c=a-b
print(c)

[-3 -3 -3]


In [33]:
c=a*b

In [34]:
print(c)

[ 4 10 18]


In [35]:
c=a/b
print(c)

[0.25 0.4  0.5 ]


In [36]:
c=a**2

In [37]:
print(c)

[1 4 9]


In [39]:
vector1=np.array([1,2,3])
vector1*1.6

array([1.6, 3.2, 4.8])