In [1]:
import numpy as np

In [2]:
import matplotlib as plt

In [19]:
from utils import plot_lines

In [6]:
A = np.array([
        [-1, 3],
        [3, 2]
    ], dtype=np.dtype(float))

b = np.array([7, 1], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

Matrix A:
[[-1.  3.]
 [ 3.  2.]]

Array b:
[7. 1.]


In [7]:
print(f"Shape A: {np.shape(A)}")
print(f"Shape b: {np.shape(b)}")

Shape A: (2, 2)
Shape b: (2,)


In [8]:
x=np.linalg.solve(A,b)
print(f"solution:{x}")

solution:[-1.  2.]


In [10]:
d=np.linalg.det(A)
print(f"Determinant of A:{d:.2f}")

Determinant of A:-11.00


In [12]:
A_system=np.hstack((A,b.reshape(2,1)))
print(A_system)

[[-1.  3.  7.]
 [ 3.  2.  1.]]


In [13]:
print(A_system[1])

[3. 2. 1.]


In [20]:
plot_lines(A_system)

TypeError: plot_lines() missing 1 required positional argument: 'y'

In [21]:
import numpy as np
import matplotlib.pyplot as plt
from utils import plot_lines


In [22]:
A = np.array([
        [-1, 3],
        [3, 2]
    ], dtype=np.dtype(float))

b = np.array([7, 1], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)


Matrix A:
[[-1.  3.]
 [ 3.  2.]]

Array b:
[7. 1.]


In [23]:
print(f"Shape A: {np.shape(A)}")
print(f"Shape b: {np.shape(b)}")


Shape A: (2, 2)
Shape b: (2,)


In [24]:
x = np.linalg.solve(A, b)
print(f"solution: {x}")


solution: [-1.  2.]


In [25]:
d = np.linalg.det(A)
print(f"Determinant of A: {d:.2f}")


Determinant of A: -11.00


In [26]:
A_system = np.hstack((A, b.reshape(2, 1)))
print(A_system)


[[-1.  3.  7.]
 [ 3.  2.  1.]]


In [27]:
print(A_system[1])


[3. 2. 1.]


In [28]:
# Example usage of plot_lines
plot_lines(A_system)

TypeError: plot_lines() missing 1 required positional argument: 'y'

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from utils import plot_lines


In [ ]:
A = np.array([
        [-1, 3],
        [3, 2]
    ], dtype=np.dtype(float))

b = np.array([7, 1], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)


In [ ]:
print(f"Shape A: {np.shape(A)}")
print(f"Shape b: {np.shape(b)}")


In [ ]:
x = np.linalg.solve(A, b)
print(f"solution: {x}")


In [ ]:
d = np.linalg.det(A)
print(f"Determinant of A: {d:.2f}")


In [ ]:
A_system = np.hstack((A, b.reshape(2, 1)))
print(A_system)


In [ ]:
print(A_system[1])


In [29]:
# Example usage of plot_lines
plot_lines(A_system)

TypeError: plot_lines() missing 1 required positional argument: 'y'

In [30]:
import numpy as np
import matplotlib.pyplot as plt
from utils import plot_lines


In [31]:
A = np.array([
        [-1, 3],
        [3, 2]
    ], dtype=np.dtype(float))

b = np.array([7, 1], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)


Matrix A:
[[-1.  3.]
 [ 3.  2.]]

Array b:
[7. 1.]


In [32]:
print(f"Shape A: {np.shape(A)}")
print(f"Shape b: {np.shape(b)}")


Shape A: (2, 2)
Shape b: (2,)


In [33]:
x = np.linalg.solve(A, b)
print(f"solution: {x}")


solution: [-1.  2.]


In [34]:
d = np.linalg.det(A)
print(f"Determinant of A: {d:.2f}")


Determinant of A: -11.00


In [35]:
A_system = np.hstack((A, b.reshape(2, 1)))
print(A_system)


[[-1.  3.  7.]
 [ 3.  2.  1.]]


In [36]:
print(A_system[1])


[3. 2. 1.]


In [37]:
# Example usage of plot_lines
plot_lines(A_system)

TypeError: plot_lines() missing 1 required positional argument: 'y'

In [38]:
import numpy as np
import matplotlib.pyplot as plt
from utils import plot_lines


In [39]:
A = np.array([
        [-1, 3],
        [3, 2]
    ], dtype=np.dtype(float))

b = np.array([7, 1], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)


Matrix A:
[[-1.  3.]
 [ 3.  2.]]

Array b:
[7. 1.]


In [40]:
print(f"Shape A: {np.shape(A)}")
print(f"Shape b: {np.shape(b)}")


Shape A: (2, 2)
Shape b: (2,)


In [41]:
x = np.linalg.solve(A, b)
print(f"solution: {x}")


solution: [-1.  2.]


In [42]:
d = np.linalg.det(A)
print(f"Determinant of A: {d:.2f}")


Determinant of A: -11.00


In [43]:
A_system = np.hstack((A, b.reshape(2, 1)))
print(A_system)


[[-1.  3.  7.]
 [ 3.  2.  1.]]


In [44]:
print(A_system[1])


[3. 2. 1.]


In [45]:
# Example usage of plot_lines
plot_lines(A_system)

TypeError: plot_lines() missing 1 required positional argument: 'y'